object DWNewStateUser: TAspDWindow
  Left = 386
  Top = 752
  Width = 183
  Height = 169
  OnDirectPaint = DWNewStateUserDirectPaint
  OnMouseMove = DWNewStateUserMouseMove
  OnInitialize = DWNewStateWinInitialize
  DParent = DBackground
  Visible = False
  GTop = 70
  GLeft = 255
  GHeight = 365
  GWidth = 288
  EnableFocus = False
  ClickCount = csNone
  Floating = True
  object DLNewStateUserName: TAspDLabel
    Left = 53
    Top = 5
    Width = 60
    Height = 14
    OnClick = DLNewStateUserNameClick
    DParent = DWNewStateUser
    Visible = True
    GTop = 38
    GLeft = 92
    GHeight = 12
    GWidth = 100
    EnableFocus = False
    Color = clBlack
    Alignment = taCenter
    Down = False
    AutoSize = False
    UpColor = clWhite
    HotColor = clWhite
    DisabledColor = 10070188
    DownColor = clRed
    BackgroundColor = clWhite
    BorderColor = 6325392
    HotBorderColor = 5805240
    DownBorderColor = 5805240
    BoldColor = 263172
    UseTick = 0
    BoldFont = False
    DrawBackground = False
    Border = False
    ClickCount = csNone
    Style = bsButton
  end
  object DBNewStateUserClose: TAspDButton
    Left = 166
    Top = 4
    Width = 14
    Height = 16
    OnDirectPaint = DBNewStateWinCloseDirectPaint
    OnClick = DBNewStateWinCloseClick
    OnInitialize = DWhisperCloseInitialize
    Caption = 'X'
    DParent = DWNewStateUser
    Visible = True
    GTop = 14
    GLeft = 257
    GHeight = 0
    GWidth = 0
    EnableFocus = False
    ClickCount = csNorm
    OnClickSound = DLoginNewClickSound
  end
  object DPNewStateUserTab: TAspDPageControl
    Left = 2
    Top = 22
    Width = 175
    Height = 145
    DParent = DWNewStateUser
    Visible = True
    GTop = 83
    GLeft = 6
    GHeight = 266
    GWidth = 260
    EnableFocus = False
    
    ClickCount = csNone
    Floating = False
    ActivePage = 0
    TabLeft = 4
    TabTop = 4
    TabWidth = 168
    TabHeight = 138
    TabGLeft = 0
    TabGTop = 0
    TabGWidth = 260
    TabGHeight = 266
    object DWNewStateUserTab1: TAspDWindow
      Left = 4
      Top = 4
      Width = 168
      Height = 138
      DParent = DPNewStateUserTab
      Visible = True
      GTop = 0
      GLeft = 0
      GHeight = 266
      GWidth = 260
      EnableFocus = False
      
      ClickCount = csNone
      Floating = False
      DPageControl = DPNewStateUserTab
      object DPNewStateUserPage: TAspDPageControl
        Left = 23
        Top = 6
        Width = 138
        Height = 129
        DParent = DWNewStateUserTab1
        Visible = True
        GTop = 0
        GLeft = 28
        GHeight = 266
        GWidth = 236
        EnableFocus = False
        
        ClickCount = csNone
        Floating = False
        ActivePage = 1
        TabLeft = 4
        TabTop = 4
        TabWidth = 130
        TabHeight = 125
        TabGLeft = 0
        TabGTop = 0
        TabGWidth = 236
        TabGHeight = 266
        object DWNewStateUserPageTab1: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateUserPageTab1DirectPaint
          OnMouseMove = DWNewStateUserMouseMove
          OnInitialize = DWNewStateWinPageTab1Initialize
          DParent = DPNewStateUserPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateUserPage
          object DBNewSUHelmet: TAspDButton
            Left = 52
            Top = 8
            Width = 16
            Height = 17
            OnMouseMove = DBNewSUWeaponMouseMove
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 50
            GLeft = 95
            GHeight = 26
            GWidth = 60
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUDress: TAspDButton
            Left = 52
            Top = 31
            Width = 16
            Height = 61
            OnMouseMove = DBNewSUWeaponMouseMove
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 82
            GLeft = 97
            GHeight = 112
            GWidth = 53
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSULight: TAspDButton
            Left = 14
            Top = 35
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #21195#31456
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 97
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUArmRingR: TAspDButton
            Left = 14
            Top = 56
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #21491#25163
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 142
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSURingR: TAspDButton
            Left = 14
            Top = 77
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #21491#25106
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 186
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUNecklace: TAspDButton
            Left = 74
            Top = 35
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #39033#38142
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 97
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUArmRingL: TAspDButton
            Left = 74
            Top = 56
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #24038#25163
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 142
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSURingL: TAspDButton
            Left = 74
            Top = 77
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #24038#25106
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 185
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUBujuk: TAspDButton
            Left = 8
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #31526
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 227
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUBelt: TAspDButton
            Left = 32
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #33136
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 227
            GLeft = 51
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUBoots: TAspDButton
            Left = 56
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #38772
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 227
            GLeft = 99
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSUCharm: TAspDButton
            Left = 96
            Top = 98
            Width = 15
            Height = 15
            OnDirectPaint = DBNewSUNecklaceDirectPaint
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #23453
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 227
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DLNewStateUserGuildName: TAspDLabel
            Left = 86
            Top = 6
            Width = 30
            Height = 10
            OnClick = DLNewStateUserGuildNameClick
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 6
            GLeft = 46
            GHeight = 12
            GWidth = 100
            EnableFocus = False
            Color = clBlack
            Alignment = taCenter
            Down = False
            AutoSize = True
            UpColor = clWhite
            HotColor = clWhite
            DisabledColor = 10070188
            DownColor = clRed
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DBNewSUWeapon: TAspDButton
            Left = 19
            Top = 3
            Width = 14
            Height = 26
            OnMouseMove = DBNewSUWeaponMouseMove
            Caption = #27494
            DParent = DWNewStateUserPageTab1
            Visible = True
            GTop = 0
            GLeft = 32
            GHeight = 150
            GWidth = 60
            EnableFocus = False
            ClickCount = csNone
          end
        end
        object DWNewStateUserPageTab2: TAspDWindow
          Left = 4
          Top = 4
          Width = 130
          Height = 125
          OnDirectPaint = DWNewStateUserPageTab2DirectPaint
          OnMouseMove = DWNewStateUserMouseMove
          OnInitialize = DWNewStateWinPageTab4Initialize
          DParent = DPNewStateUserPage
          Visible = True
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateUserPage
          object DBNewUserTitleMan: TAspDButton
            Left = 14
            Top = 12
            Width = 18
            Height = 17
            OnDirectPaint = DBNewUserTitleManDirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitleManInitialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 7
            GLeft = 29
            GHeight = 36
            GWidth = 36
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserTitle1: TAspDButton
            Left = 9
            Top = 35
            Width = 15
            Height = 14
            OnDirectPaint = DBNewUserTitle1DirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitle1Initialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 75
            GLeft = 12
            GHeight = 28
            GWidth = 28
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserTitle2: TAspDButton
            Tag = 1
            Left = 9
            Top = 53
            Width = 15
            Height = 14
            OnDirectPaint = DBNewUserTitle1DirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitle1Initialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 114
            GLeft = 12
            GHeight = 28
            GWidth = 28
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserTitle3: TAspDButton
            Tag = 2
            Left = 9
            Top = 70
            Width = 15
            Height = 14
            OnDirectPaint = DBNewUserTitle1DirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitle1Initialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 153
            GLeft = 12
            GHeight = 28
            GWidth = 28
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserTitle4: TAspDButton
            Tag = 3
            Left = 9
            Top = 88
            Width = 15
            Height = 14
            OnDirectPaint = DBNewUserTitle1DirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitle1Initialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 192
            GLeft = 12
            GHeight = 28
            GWidth = 28
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserTitle5: TAspDButton
            Tag = 4
            Left = 9
            Top = 107
            Width = 15
            Height = 14
            OnDirectPaint = DBNewUserTitle1DirectPaint
            OnMouseMove = DBNewUserTitle1MouseMove
            OnInitialize = DBNewTitle1Initialize
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 231
            GLeft = 12
            GHeight = 28
            GWidth = 28
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserPrevTitle: TAspDButton
            Left = 30
            Top = 48
            Width = 12
            Height = 16
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewUserPrevTitleClick
            OnInitialize = DBNewPrevTitleInitialize
            Caption = #8743
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 140
            GLeft = 118
            GHeight = 23
            GWidth = 14
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewUserNextTitle: TAspDButton
            Left = 30
            Top = 70
            Width = 12
            Height = 16
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewUserPrevTitleClick
            OnInitialize = DBNewNextTitleInitialize
            Caption = #8744
            DParent = DWNewStateUserPageTab2
            Visible = True
            GTop = 172
            GLeft = 118
            GHeight = 23
            GWidth = 14
            EnableFocus = False
            ClickCount = csNone
          end
        end
      end
      object DBNewStateUserPage: TAspDButton
        Left = 5
        Top = 6
        Width = 12
        Height = 121
        OnDirectPaint = DBNewStateUserPageDirectPaint
        OnMouseMove = DWNewStateUserMouseMove
        OnClick = DBNewStateUserPageClick
        OnInitialize = DBNewStateUserPageInitialize
        DParent = DWNewStateUserTab1
        Visible = True
        GTop = 0
        GLeft = 0
        GHeight = 264
        GWidth = 24
        EnableFocus = False
        ClickCount = csNone
      end
    end
  end
end

