object DWNewStateHero: TAspDWindow
  Left = 197
  Top = 752
  Width = 183
  Height = 169
  OnDirectPaint = DWNewStateHeroDirectPaint
  OnMouseMove = DWNewStateHeroMouseMove
  OnInitialize = DWNewStateHeroInitialize
  DParent = DBackground
  Visible = False
  GTop = 0
  GLeft = 512
  GHeight = 365
  GWidth = 287
  EnableFocus = False
  ClickCount = csNone
  Floating = True
  object DBNewStateHeroTab1: TAspDButton
    Left = 12
    Top = 4
    Width = 33
    Height = 16
    OnMouseMove = DWNewStateWinMouseMove
    OnClick = DBNewStateTab1Click
    DParent = DWNewStateHero
    Visible = False
    GTop = 56
    GLeft = 60
    GHeight = 20
    GWidth = 68
    EnableFocus = False
    ClickCount = csGlass
    OnClickSound = DLoginNewClickSound
  end
  object DBNewStateHeroTab2: TAspDButton
    Tag = 1
    Left = 67
    Top = 4
    Width = 33
    Height = 16
    OnMouseMove = DWNewStateWinMouseMove
    OnClick = DBNewStateTab1Click
    DParent = DWNewStateHero
    Visible = False
    GTop = 56
    GLeft = 129
    GHeight = 20
    GWidth = 68
    EnableFocus = False
    ClickCount = csGlass
    OnClickSound = DLoginNewClickSound
  end
  object DBNewStateHeroClose: TAspDButton
    Left = 166
    Top = 4
    Width = 14
    Height = 16
    OnDirectPaint = DBNewStateWinCloseDirectPaint
    OnClick = DBNewStateWinCloseClick
    OnInitialize = DWhisperCloseInitialize
    Caption = 'X'
    DParent = DWNewStateHero
    Visible = True
    GTop = 30
    GLeft = 257
    GHeight = 0
    GWidth = 0
    EnableFocus = False
    ClickCount = csNorm
    OnClickSound = DLoginNewClickSound
  end
  object DPNewStateHeroTab: TAspDPageControl
    Left = 2
    Top = 22
    Width = 175
    Height = 145
    DParent = DWNewStateHero
    Visible = True
    GTop = 83
    GLeft = 6
    GHeight = 266
    GWidth = 260
    EnableFocus = False
    
    ClickCount = csNone
    Floating = False
    ActivePage = 1
    TabLeft = 4
    TabTop = 4
    TabWidth = 168
    TabHeight = 138
    TabGLeft = 0
    TabGTop = 0
    TabGWidth = 260
    TabGHeight = 266
    object DWNewStateHeroTab1: TAspDWindow
      Left = 4
      Top = 4
      Width = 0
      Height = 0
      DParent = DPNewStateHeroTab
      Visible = False
      GTop = 0
      GLeft = 0
      GHeight = 266
      GWidth = 260
      EnableFocus = False
      
      ClickCount = csNone
      Floating = False
      DPageControl = DPNewStateHeroTab
      object DPNewStateHeroPage: TAspDPageControl
        Left = 23
        Top = 6
        Width = 138
        Height = 129
        DParent = DWNewStateHeroTab1
        Visible = True
        GTop = 0
        GLeft = 28
        GHeight = 266
        GWidth = 236
        EnableFocus = False
        
        ClickCount = csNone
        Floating = False
        ActivePage = 3
        TabLeft = 4
        TabTop = 4
        TabWidth = 130
        TabHeight = 125
        TabGLeft = 0
        TabGTop = 0
        TabGWidth = 236
        TabGHeight = 266
        object DWNewStateHeroPageTab1: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroPageTab1DirectPaint
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateHeroPageTab1Initialize
          DParent = DPNewStateHeroPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroPage
          object DBNewSHHelmet: TAspDButton
            Left = 52
            Top = 8
            Width = 16
            Height = 17
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 50
            GLeft = 95
            GHeight = 26
            GWidth = 60
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHDress: TAspDButton
            Left = 52
            Top = 31
            Width = 16
            Height = 61
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 82
            GLeft = 97
            GHeight = 112
            GWidth = 53
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHLight: TAspDButton
            Left = 14
            Top = 35
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #21195#31456
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 97
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHArmRingR: TAspDButton
            Left = 14
            Top = 56
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #21491#25163
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 142
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHRingR: TAspDButton
            Left = 14
            Top = 77
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #21491#25106
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 186
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHNecklace: TAspDButton
            Left = 74
            Top = 35
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #39033#38142
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 97
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHArmRingL: TAspDButton
            Left = 74
            Top = 56
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #24038#25163
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 142
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHRingL: TAspDButton
            Left = 74
            Top = 77
            Width = 32
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #24038#25106
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 185
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHBujuk: TAspDButton
            Left = 8
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #31526
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 227
            GLeft = 2
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHBelt: TAspDButton
            Left = 32
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #33136
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 227
            GLeft = 51
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHBoots: TAspDButton
            Left = 56
            Top = 98
            Width = 18
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #38772
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 227
            GLeft = 99
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHCharm: TAspDButton
            Left = 96
            Top = 98
            Width = 15
            Height = 15
            OnDirectPaint = DBNewSHNecklaceDirectPaint
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #23453
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 227
            GLeft = 195
            GHeight = 31
            GWidth = 34
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewSHWeapon: TAspDButton
            Left = 19
            Top = 3
            Width = 14
            Height = 26
            OnMouseMove = DBNewSHWeaponMouseMove
            OnClick = DBNewSHWeaponClick
            Caption = #27494
            DParent = DWNewStateHeroPageTab1
            Visible = True
            GTop = 0
            GLeft = 32
            GHeight = 150
            GWidth = 60
            EnableFocus = False
            ClickCount = csNone
          end
        end
        object DWNewStateHeroPageTab2: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroPageTab2DirectPaint
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateWinPageTab2Initialize
          DParent = DPNewStateHeroPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroPage
          object DBNewHeroLiquorProgress: TAspDButton
            Left = 15
            Top = 38
            Width = 92
            Height = 15
            OnDirectPaint = DBNewHeroLiquorProgressDirectPaint
            OnMouseMove = DBotFactionMouseMove
            OnInitialize = DBNewLiquorProgressInitialize
            Caption = #37202#37327#25552#21319#36827#24230
            DParent = DWNewStateHeroPageTab2
            Visible = True
            GTop = 139
            GLeft = 150
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = clYellow
            ClickCount = csNone
          end
        end
        object DWNewStateHeroPageTab3: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroPageTab3DirectPaint
          OnInitialize = DWNewStateWinPageTab3Initialize
          DParent = DPNewStateHeroPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroPage
        end
        object DWNewStateHeroPageTab5: TAspDWindow
          Left = 4
          Top = 4
          Width = 130
          Height = 125
          OnDirectPaint = DWNewStateHeroPageTab5DirectPaint
          OnMouseMove = DWNewStateWinMouseMove
          OnInitialize = DWNewStateWinPageTab5Initialize
          DParent = DPNewStateHeroPage
          Visible = True
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroPage
          object DBNewHeroStMag1: TAspDButton
            Left = 11
            Top = 5
            Width = 15
            Height = 16
            OnDirectPaint = DBNewHeroStMag1DirectPaint
            OnMouseMove = DBNewHeroStMag1MouseMove
            OnClick = DBNewHeroStMag1Click
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 13
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStMag2: TAspDButton
            Tag = 1
            Left = 11
            Top = 27
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStMag1DirectPaint
            OnMouseMove = DBNewHeroStMag1MouseMove
            OnClick = DBNewHeroStMag1Click
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 65
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStMag3: TAspDButton
            Tag = 2
            Left = 11
            Top = 48
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStMag1DirectPaint
            OnMouseMove = DBNewHeroStMag1MouseMove
            OnClick = DBNewHeroStMag1Click
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 115
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStMag4: TAspDButton
            Tag = 3
            Left = 11
            Top = 69
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStMag1DirectPaint
            OnMouseMove = DBNewHeroStMag1MouseMove
            OnClick = DBNewHeroStMag1Click
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 165
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStMag5: TAspDButton
            Tag = 4
            Left = 11
            Top = 90
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStMag1DirectPaint
            OnMouseMove = DBNewHeroStMag1MouseMove
            OnClick = DBNewHeroStMag1Click
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 215
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStPageUp: TAspDButton
            Tag = 3
            Left = 32
            Top = 103
            Width = 19
            Height = 13
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewHeroStPageUpClick
            OnInitialize = DBNewStPageUpInitialize
            Caption = '<'
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 250
            GLeft = 66
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStPageDown: TAspDButton
            Tag = 4
            Left = 57
            Top = 103
            Width = 19
            Height = 13
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewHeroStPageUpClick
            OnInitialize = DBNewStPageDownInitialize
            Caption = '>'
            DParent = DWNewStateHeroPageTab5
            Visible = True
            GTop = 250
            GLeft = 131
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroJQExp: TAspDButton
            Left = 74
            Top = 45
            Width = 27
            Height = 12
            OnDirectPaint = DBNewJQExpDirectPaint
            OnMouseMove = DBNewJQExpMouseMove
            OnInitialize = JQExpInitialize
            DParent = DWNewStateHeroPageTab5
            Visible = False
            GTop = 0
            GLeft = 0
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csStone
          end
        end
      end
      object DBNewStateHeroPage: TAspDButton
        Left = 5
        Top = 6
        Width = 12
        Height = 121
        OnDirectPaint = DBNewStateHeroPageDirectPaint
        OnMouseMove = DWNewStateHeroMouseMove
        OnClick = DBNewStateHeroPageClick
        OnInitialize = DBNewStateHeroPageInitialize
        DParent = DWNewStateHeroTab1
        Visible = True
        GTop = 0
        GLeft = 0
        GHeight = 264
        GWidth = 24
        EnableFocus = False
        ClickCount = csNone
      end
    end
    object DWNewStateHeroTab2: TAspDWindow
      Left = 4
      Top = 4
      Width = 168
      Height = 138
      DParent = DPNewStateHeroTab
      Visible = True
      GTop = 0
      GLeft = 0
      GHeight = 266
      GWidth = 260
      EnableFocus = False
      
      ClickCount = csNone
      Floating = False
      DPageControl = DPNewStateHeroTab
      object DBNewStateHeroNGPage: TAspDButton
        Left = 5
        Top = 6
        Width = 12
        Height = 121
        OnDirectPaint = DBNewStateHeroNGPageDirectPaint
        OnMouseMove = DWNewStateHeroMouseMove
        OnClick = DBNewStateHeroNGPageClick
        OnInitialize = DBNewStateWinNGPageInitialize
        DParent = DWNewStateHeroTab2
        Visible = True
        GTop = 0
        GLeft = 0
        GHeight = 264
        GWidth = 24
        EnableFocus = False
        ClickCount = csNone
      end
      object DPNewStateHeroNGPage: TAspDPageControl
        Left = 23
        Top = 6
        Width = 138
        Height = 129
        DParent = DWNewStateHeroTab2
        Visible = True
        GTop = 0
        GLeft = 28
        GHeight = 266
        GWidth = 236
        EnableFocus = False
        
        ClickCount = csNone
        Floating = False
        ActivePage = 3
        TabLeft = 4
        TabTop = 4
        TabWidth = 130
        TabHeight = 125
        TabGLeft = 0
        TabGTop = 0
        TabGWidth = 236
        TabGHeight = 266
        object DWNewStateHeroNGPageTab1: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroNGPageTab1DirectPaint
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateWinNGPageTab1Initialize
          DParent = DPNewStateHeroNGPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroNGPage
        end
        object DWNewStateHeroNGPageTab2: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroNGPageTab2DirectPaint
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateWinNGPageTab2Initialize
          DParent = DPNewStateHeroNGPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroNGPage
          object DBNewHeroStNGMag1: TAspDButton
            Left = 11
            Top = 5
            Width = 15
            Height = 16
            OnDirectPaint = DBNewHeroStNGMag1DirectPaint
            OnMouseMove = DBNewHeroStNGMag1MouseMove
            OnClick = DBNewHeroStNGMag1Click
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 13
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGMag2: TAspDButton
            Tag = 1
            Left = 11
            Top = 27
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStNGMag1DirectPaint
            OnMouseMove = DBNewHeroStNGMag1MouseMove
            OnClick = DBNewHeroStNGMag1Click
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 65
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGMag3: TAspDButton
            Tag = 2
            Left = 11
            Top = 48
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStNGMag1DirectPaint
            OnMouseMove = DBNewHeroStNGMag1MouseMove
            OnClick = DBNewHeroStNGMag1Click
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 115
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGMag4: TAspDButton
            Tag = 3
            Left = 11
            Top = 69
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStNGMag1DirectPaint
            OnMouseMove = DBNewHeroStNGMag1MouseMove
            OnClick = DBNewHeroStNGMag1Click
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 165
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGMag5: TAspDButton
            Tag = 4
            Left = 11
            Top = 90
            Width = 15
            Height = 15
            OnDirectPaint = DBNewHeroStNGMag1DirectPaint
            OnMouseMove = DBNewHeroStNGMag1MouseMove
            OnClick = DBNewHeroStNGMag1Click
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 215
            GLeft = 18
            GHeight = 33
            GWidth = 31
            EnableFocus = False
            ClickCount = csStone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGPageUp: TAspDButton
            Tag = 3
            Left = 32
            Top = 103
            Width = 19
            Height = 13
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewHeroStNGPageUpClick
            OnInitialize = DBNewStPageUpInitialize
            Caption = '<'
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 250
            GLeft = 66
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
            OnClickSound = DLoginNewClickSound
          end
          object DBNewHeroStNGPageDown: TAspDButton
            Tag = 4
            Left = 57
            Top = 103
            Width = 19
            Height = 13
            OnDirectPaint = DBXinFaNamePrevDirectPaint
            OnClick = DBNewHeroStNGPageUpClick
            OnInitialize = DBNewStPageDownInitialize
            Caption = '>'
            DParent = DWNewStateHeroNGPageTab2
            Visible = True
            GTop = 250
            GLeft = 131
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
            OnClickSound = DLoginNewClickSound
          end
          object DLNewHeroNGUpLevel1: TAspDLabel
            Left = 48
            Top = 5
            Width = 26
            Height = 15
            OnMouseMove = DLNewHeroNGUpLevel1MouseMove
            OnClick = DLNewHeroNGUpLevel1Click
            OnInitialize = DLNGUpLevel1Initialize
            Caption = #21319#32423
            DParent = DWNewStateHeroNGPageTab2
            Visible = False
            GTop = 15
            GLeft = 169
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = 9226223
            Alignment = taCenter
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroNGUpLevel2: TAspDLabel
            Tag = 1
            Left = 48
            Top = 24
            Width = 26
            Height = 15
            OnMouseMove = DLNewHeroNGUpLevel1MouseMove
            OnClick = DLNewHeroNGUpLevel1Click
            OnInitialize = DLNGUpLevel1Initialize
            Caption = #21319#32423
            DParent = DWNewStateHeroNGPageTab2
            Visible = False
            GTop = 66
            GLeft = 169
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = 9226223
            Alignment = taCenter
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroNGUpLevel3: TAspDLabel
            Tag = 2
            Left = 48
            Top = 42
            Width = 26
            Height = 15
            OnMouseMove = DLNewHeroNGUpLevel1MouseMove
            OnClick = DLNewHeroNGUpLevel1Click
            OnInitialize = DLNGUpLevel1Initialize
            Caption = #21319#32423
            DParent = DWNewStateHeroNGPageTab2
            Visible = False
            GTop = 117
            GLeft = 169
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = 9226223
            Alignment = taCenter
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroNGUpLevel4: TAspDLabel
            Tag = 3
            Left = 48
            Top = 60
            Width = 26
            Height = 15
            OnMouseMove = DLNewHeroNGUpLevel1MouseMove
            OnClick = DLNewHeroNGUpLevel1Click
            OnInitialize = DLNGUpLevel1Initialize
            Caption = #21319#32423
            DParent = DWNewStateHeroNGPageTab2
            Visible = False
            GTop = 168
            GLeft = 169
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = 9226223
            Alignment = taCenter
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroNGUpLevel5: TAspDLabel
            Tag = 4
            Left = 48
            Top = 78
            Width = 26
            Height = 15
            OnMouseMove = DLNewHeroNGUpLevel1MouseMove
            OnClick = DLNewHeroNGUpLevel1Click
            OnInitialize = DLNGUpLevel1Initialize
            Caption = #21319#32423
            DParent = DWNewStateHeroNGPageTab2
            Visible = False
            GTop = 219
            GLeft = 169
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            Color = 9226223
            Alignment = taCenter
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = False
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
        end
        object DWNewStateHeroNGPageTab3: TAspDWindow
          Left = 4
          Top = 4
          Width = 0
          Height = 0
          OnDirectPaint = DWNewStateHeroNGPageTab3DirectPaint
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateWinNGPageTab3Initialize
          DParent = DPNewStateHeroNGPage
          Visible = False
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroNGPage
          object DBNewHeroPointIcon1: TAspDButton
            Left = 18
            Top = 13
            Width = 21
            Height = 16
            OnDirectPaint = DBNewHeroPointIcon1DirectPaint
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 42
            GLeft = 69
            GHeight = 23
            GWidth = 24
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointIcon2: TAspDButton
            Tag = 1
            Left = 18
            Top = 33
            Width = 21
            Height = 16
            OnDirectPaint = DBNewHeroPointIcon1DirectPaint
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 71
            GLeft = 68
            GHeight = 23
            GWidth = 24
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointIcon3: TAspDButton
            Tag = 2
            Left = 18
            Top = 53
            Width = 21
            Height = 16
            OnDirectPaint = DBNewHeroPointIcon1DirectPaint
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 96
            GLeft = 70
            GHeight = 23
            GWidth = 24
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointIcon4: TAspDButton
            Tag = 3
            Left = 18
            Top = 73
            Width = 21
            Height = 16
            OnDirectPaint = DBNewHeroPointIcon1DirectPaint
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 118
            GLeft = 77
            GHeight = 23
            GWidth = 24
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointIcon5: TAspDButton
            Tag = 4
            Left = 18
            Top = 93
            Width = 21
            Height = 16
            OnDirectPaint = DBNewHeroPointIcon1DirectPaint
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 100
            GLeft = 84
            GHeight = 23
            GWidth = 24
            EnableFocus = True
            ClickCount = csNone
          end
          object DLNewHeroPointName1: TAspDLabel
            Left = 57
            Top = 13
            Width = 21
            Height = 16
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 47
            GLeft = 113
            GHeight = 12
            GWidth = 24
            EnableFocus = False
            Color = clBlack
            Alignment = taLeftJustify
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = True
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroPointName2: TAspDLabel
            Tag = 1
            Left = 57
            Top = 33
            Width = 21
            Height = 16
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 76
            GLeft = 112
            GHeight = 12
            GWidth = 24
            EnableFocus = False
            Color = clBlack
            Alignment = taLeftJustify
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = True
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroPointName3: TAspDLabel
            Tag = 2
            Left = 57
            Top = 53
            Width = 21
            Height = 16
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 101
            GLeft = 34
            GHeight = 12
            GWidth = 24
            EnableFocus = False
            Color = clBlack
            Alignment = taLeftJustify
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = True
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroPointName4: TAspDLabel
            Tag = 3
            Left = 57
            Top = 73
            Width = 21
            Height = 16
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 123
            GLeft = 38
            GHeight = 12
            GWidth = 24
            EnableFocus = False
            Color = clBlack
            Alignment = taLeftJustify
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = True
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DLNewHeroPointName5: TAspDLabel
            Tag = 4
            Left = 57
            Top = 93
            Width = 21
            Height = 16
            OnMouseMove = DBNewHeroPointIcon1MouseMove
            OnClick = DBNewHeroPointIcon1Click
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 104
            GLeft = 118
            GHeight = 12
            GWidth = 24
            EnableFocus = False
            Color = clBlack
            Alignment = taLeftJustify
            Down = True
            AutoSize = True
            UpColor = 9226223
            HotColor = 11393007
            DisabledColor = 10070188
            DownColor = 4892399
            BackgroundColor = clWhite
            BorderColor = 6325392
            HotBorderColor = 5805240
            DownBorderColor = 5805240
            BoldColor = 263172
            UseTick = 0
            BoldFont = True
            DrawBackground = False
            Border = False
            ClickCount = csNone
            Style = bsButton
          end
          object DBNewHeroPointPage1: TAspDButton
            Left = 98
            Top = 32
            Width = 26
            Height = 15
            OnDirectPaint = DBNewHeroPointPage1DirectPaint
            OnClick = DBNewHeroPointPage1Click
            OnInitialize = DBNewWinPointPage1Initialize
            Caption = #20914#33033
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 24
            GLeft = 196
            GHeight = 22
            GWidth = 32
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointPage2: TAspDButton
            Tag = 1
            Left = 98
            Top = 51
            Width = 26
            Height = 15
            OnDirectPaint = DBNewHeroPointPage1DirectPaint
            OnClick = DBNewHeroPointPage1Click
            OnInitialize = DBNewWinPointPage1Initialize
            Caption = #38452#36343
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 47
            GLeft = 196
            GHeight = 22
            GWidth = 32
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointPage3: TAspDButton
            Tag = 2
            Left = 98
            Top = 70
            Width = 26
            Height = 15
            OnDirectPaint = DBNewHeroPointPage1DirectPaint
            OnClick = DBNewHeroPointPage1Click
            OnInitialize = DBNewWinPointPage1Initialize
            Caption = #38452#32500
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 70
            GLeft = 196
            GHeight = 22
            GWidth = 32
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointPage4: TAspDButton
            Tag = 3
            Left = 98
            Top = 89
            Width = 26
            Height = 15
            OnDirectPaint = DBNewHeroPointPage1DirectPaint
            OnClick = DBNewHeroPointPage1Click
            OnInitialize = DBNewWinPointPage1Initialize
            Caption = #20219#33033
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 93
            GLeft = 196
            GHeight = 22
            GWidth = 32
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointPage5: TAspDButton
            Tag = 4
            Left = 98
            Top = 13
            Width = 26
            Height = 15
            OnDirectPaint = DBNewHeroPointPage1DirectPaint
            OnClick = DBNewHeroPointPage1Click
            OnInitialize = DBNewWinPointPage1Initialize
            Caption = #22855#32463
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 1
            GLeft = 196
            GHeight = 22
            GWidth = 32
            EnableFocus = True
            ClickCount = csNone
          end
          object DBNewHeroPointPractice: TAspDButton
            Left = 9
            Top = 112
            Width = 50
            Height = 10
            OnDirectPaint = DBNewWinPointPracticeDirectPaint
            OnMouseMove = DBNewHeroPointPracticeMouseMove
            OnClick = DBNewHeroPointPracticeClick
            OnInitialize = DBNewWinPointPracticeInitialize
            DParent = DWNewStateHeroNGPageTab3
            Visible = True
            GTop = 241
            GLeft = 8
            GHeight = 21
            GWidth = 60
            EnableFocus = True
            ClickCount = csNone
          end
        end
        object DWNewStateHeroNGPageTab4: TAspDWindow
          Left = 4
          Top = 4
          Width = 130
          Height = 125
          OnMouseMove = DWNewStateHeroMouseMove
          OnInitialize = DWNewStateWinNGPageTab4Initialize
          DParent = DPNewStateHeroNGPage
          Visible = True
          GTop = 0
          GLeft = 0
          GHeight = 266
          GWidth = 236
          EnableFocus = False
          
          ClickCount = csNone
          Floating = False
          DPageControl = DPNewStateHeroNGPage
          object DBNewHeroBatterTopMag1: TAspDButton
            Left = 11
            Top = 9
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterTopMag1DirectPaint
            OnMouseMove = DBNewHeroBatterTopMag1MouseMove
            OnClick = DBNewHeroBatterTopMag1Click
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 12
            GLeft = 21
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterTopMag2: TAspDButton
            Tag = 1
            Left = 31
            Top = 9
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterTopMag1DirectPaint
            OnMouseMove = DBNewHeroBatterTopMag1MouseMove
            OnClick = DBNewHeroBatterTopMag1Click
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 12
            GLeft = 75
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterTopMag3: TAspDButton
            Tag = 2
            Left = 51
            Top = 9
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterTopMag1DirectPaint
            OnMouseMove = DBNewHeroBatterTopMag1MouseMove
            OnClick = DBNewHeroBatterTopMag1Click
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 12
            GLeft = 130
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterTopMag4: TAspDButton
            Tag = 3
            Left = 71
            Top = 9
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterTopMag1DirectPaint
            OnMouseMove = DBNewHeroBatterTopMag1MouseMove
            OnClick = DBNewHeroBatterTopMag1Click
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 12
            GLeft = 185
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterRandom: TAspDButton
            Left = 41
            Top = 26
            Width = 18
            Height = 10
            Hint = #38543#26426
            OnDirectPaint = DWinBatterRandomDirectPaint
            OnMouseMove = DBNewHeroBatterTopMag1MouseMove
            OnClick = DBNewHeroBatterRandomClick
            OnInitialize = DBNewWinBatterRandomInitialize
            DParent = DWNewStateHeroNGPageTab4
            Visible = False
            GTop = 49
            GLeft = 106
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterMag1: TAspDButton
            Left = 12
            Top = 38
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterMag1DirectPaint
            OnMouseMove = DBNewHeroBatterMag1MouseMove
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 85
            GLeft = 18
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterMag2: TAspDButton
            Tag = 1
            Left = 12
            Top = 58
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterMag1DirectPaint
            OnMouseMove = DBNewHeroBatterMag1MouseMove
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 128
            GLeft = 18
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterMag3: TAspDButton
            Tag = 2
            Left = 12
            Top = 78
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterMag1DirectPaint
            OnMouseMove = DBNewHeroBatterMag1MouseMove
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 171
            GLeft = 18
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterMag4: TAspDButton
            Tag = 3
            Left = 12
            Top = 98
            Width = 16
            Height = 16
            OnDirectPaint = DBNewHeroBatterMag1DirectPaint
            OnMouseMove = DBNewHeroBatterMag1MouseMove
            DParent = DWNewStateHeroNGPageTab4
            Visible = True
            GTop = 214
            GLeft = 18
            GHeight = 30
            GWidth = 32
            EnableFocus = False
            ClickCount = csNone
          end
          object DBNewHeroBatterCom: TAspDButton
            Left = 89
            Top = 42
            Width = 17
            Height = 24
            OnDirectPaint = DBNewHeroBatterComDirectPaint
            OnMouseMove = DBNewHeroBatterComMouseMove
            OnClick = DBNewHeroBatterComClick
            OnInitialize = DWinBatterComInitialize
            DParent = DWNewStateHeroNGPageTab4
            Visible = False
            GTop = 0
            GLeft = 0
            GHeight = 0
            GWidth = 0
            EnableFocus = False
            ClickCount = csNone
          end
        end
      end
    end
  end
end

